/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-25 14:08:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.FlightDetails;
import com.dao.FlightDao;
import java.util.*;

public final class AdminActivity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.model.FlightDetails");
    _jspx_imports_classes.add("com.dao.FlightDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h2 align=\"right\">\r\n");
      out.write("		Welcome\r\n");
      out.write("		");
      out.print(request.getAttribute("admin"));
      out.write("</h2>\r\n");
      out.write("	<div align=\"right\">\r\n");
      out.write("		<a href=\"AdminController?adminLogin=logout\">logout</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<center>\r\n");
      out.write("		<h3>Add Flight Details</h3>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<form action=\"FlightController\" method=\"post\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Airline Name :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"AirLine_Name\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Flight Number :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"Flight_Number\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Source City :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"Source_City\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Destination City :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"Destination_City\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Date of Travel:</td>\r\n");
      out.write("					<td><input type=\"date\" name=\"Date_of_Travel\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Departure Time :</td>\r\n");
      out.write("					<td><input type=\"datetime-local\" name=\"Departure_time_from_source\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Arrival Time :</td>\r\n");
      out.write("					<td><input type=\"datetime-local\" name=\"Arrival_time_at_destination\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Class</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"clases\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Total Seats :</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Total_Seats\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Booked Seats : </td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Booked_Seats\" ></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Available Seats : </td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Seat_Availability\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Ticket Price</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Ticket_Price\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\" colspan=\"2\">\r\n");
      out.write("						<input type=\"submit\" value=\"Add\" name=\"b1\">\r\n");
      out.write("						<input type=\"submit\" value=\"Display\"name=\"b1\">\r\n");
      out.write("						<input type=\"submit\" value=\"Delete\" name=\"b1\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("			<thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>AirLine Name</th>\r\n");
      out.write("				<th>Flight Number</th>\r\n");
      out.write("				<th>Source City</th>\r\n");
      out.write("				<th>Destination City</th>\r\n");
      out.write("				<th>Schedule On</th>\r\n");
      out.write("				<th>Departure Time</th>\r\n");
      out.write("				<th>Arrival Time</th>\r\n");
      out.write("				<th>Total Seats</th>\r\n");
      out.write("				<th>Booked Seats</th>\r\n");
      out.write("				<th>Seats Available</th>\r\n");
      out.write("				<th>Class</th>\r\n");
      out.write("				<th>Ticket Price</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("		  ");
ArrayList<FlightDetails> flist = new FlightDao().displayAllFlight();		
			for(FlightDetails fd:flist)
			{
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getAirLine_Name() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getFlight_Number() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getSource_City() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getDestination_City() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getDate_of_Travel() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getDeparture_time_from_source() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getArrival_time_at_Destination() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getTotal_Seats() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getBooked_Seats() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getSeat_Availability() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getClases() );
      out.write("</td>\r\n");
      out.write("				<td align=\"center\">");
      out.print(fd.getTicket_Price() );
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("	</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
