/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-27 12:20:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.FlightDetails;
import com.model.User;

public final class ReviewPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.model.FlightDetails");
    _jspx_imports_classes.add("com.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("td {\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("  color: rgb(150,150,0);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"MyStyles.css\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Review Details</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<br><br>\r\n");
      out.write("	<center><h2>Review All the details and Click On Confirm to Book Tickets</h2></center>\r\n");
      out.write("	<br><hr><br><br>\r\n");
      out.write("	");

	User u = (User) request.getAttribute("u");
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	FlightDetails fd = (FlightDetails) request.getAttribute("fd");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<center>\r\n");
      out.write("		<div style=\"float: left; margin-left:25%;\">\r\n");
      out.write("			<h2>Your Details</h2>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Full Name:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"fullname\"\r\n");
      out.write("						value=\"");
      out.print(u.getUserFullName());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Email:</td>\r\n");
      out.write("					<td><input type=\"email\" name=\"email\"\r\n");
      out.write("						value=\"");
      out.print(u.getUserEmail());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">username:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"username\"\r\n");
      out.write("						value=\"");
      out.print(u.getUsername());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Age:</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"age\" value=\"");
      out.print(u.getAge());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Aadhar No:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"aadhar\"\r\n");
      out.write("						value=\"");
      out.print(u.getUserAadhar());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Country:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"country\"\r\n");
      out.write("						value=\"");
      out.print(u.getCountry());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Seat Request</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Total_Persons\" value=\"");
      out.print(request.getParameter("Total_Persons"));
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"float: right; margin-right:25%;\">\r\n");
      out.write("			<h2>Flight Details</h2>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Airline Name :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"AirLine_Name\" value=\"");
      out.print(fd.getAirLine_Name());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Flight Number :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"Flight_Number\" value=\"");
      out.print(fd.getFlight_Number());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Source City :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"Source_City\" value=\"");
      out.print(fd.getSource_City());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Destination City :</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"Destination_City\" value=\"");
      out.print(fd.getDestination_City());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Date of Travel:</td>\r\n");
      out.write("					<td><input type=\"date\" name=\"Date_of_Travel\" value=\"");
      out.print(fd.getDate_of_Travel());
      out.write("\" readonly=\"readonly\"> </td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Departure Time :</td>\r\n");
      out.write("					<td><input type=\"datetime-local\"\r\n");
      out.write("						name=\"Departure_time_from_source\" value=\"");
      out.print(fd.getDeparture_time_from_source());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Arrival Time :</td>\r\n");
      out.write("					<td><input type=\"datetime-local\"\r\n");
      out.write("						name=\"Arrival_time_at_destination\" value=\"");
      out.print(fd.getArrival_time_at_Destination());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Class</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"clases\" value=\"");
      out.print(fd.getClases());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Total Seats :</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Total_Seats\" value=\"");
      out.print(fd.getTotal_Seats());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Booked Seats :</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Booked_Seats\" value=\"");
      out.print(fd.getBooked_Seats());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Available Seats :</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Seat_Availability\" value=\"");
      out.print(fd.getSeat_Availability());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\">Ticket Price</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"Ticket_Price\" value=\"");
      out.print(fd.getTicket_Price());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</center>\r\n");
      out.write("	<center>\r\n");
      out.write("	<div style=\"margin-top: 32%;\">\r\n");
      out.write("		<form action=\"Payment.jsp\" method=\"post\">\r\n");
      out.write("			<input type=\"submit\" value=\"Confirm\" class=\"button-8\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	</center>\r\n");
      out.write("	");
session.setAttribute("u", u);
	session.setAttribute("fd", fd);
	session.setAttribute("Total_Persons", request.getParameter("Total_Persons"));
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
